### ISSUE TITLE
Can't run project setup for development

### ISSUE THREAD

**Issue by JPKairos** [linuxforphp/filebrowser#9]
I can't start the project setup for development. If I run
`npm run serve`
I receive
#######
sudo npm run serve

filebrowser@0.1.0 serve
concurrently "php -S localhost:8081" "vue-cli-service serve"

[0] [Mon Jul 29 17:28:12 2024] PHP 8.2.20 Development Server (http://localhost:8081) started
[1]  INFO  Starting development server...
[1]  ERROR  ValidationError: Progress Plugin Invalid Options
[1]
[1]         options should NOT have additional properties
[1]         options should NOT have additional properties
[1]         options should NOT have additional properties
[1]         options should pass "instanceof" keyword validation
[1]         options should match exactly one schema in oneOf
[1]
[1] ValidationError: Progress Plugin Invalid Options
[1]
[1] options should NOT have additional properties
[1] options should NOT have additional properties
[1] options should NOT have additional properties
[1] options should pass "instanceof" keyword validation
[1] options should match exactly one schema in oneOf
[1]
[1]     at validateOptions (/opt/fb_container/filebrowser/node_modules/webpack/node_modules/schema-utils/src/validateOptions.js:32:11)
[1]     at new ProgressPlugin (/opt/fb_container/filebrowser/node_modules/webpack/lib/ProgressPlugin.js:62:3)
[1]     at new Progress (/opt/fb_container/filebrowser/node_modules/progress-webpack-plugin/index.js:25:21)
[1]     at new progressPlugin (/opt/fb_container/filebrowser/node_modules/progress-webpack-plugin/index.js:127:10)
[1]     at /opt/fb_container/filebrowser/node_modules/webpack-chain/src/Plugin.js:14:18
[1]     at module.exports.toConfig (/opt/fb_container/filebrowser/node_modules/webpack-chain/src/Plugin.js:78:22)
[1]     at /opt/fb_container/filebrowser/node_modules/webpack-chain/src/Config.js:129:63
[1]     at Array.map (<anonymous>)
[1]     at module.exports.toConfig (/opt/fb_container/filebrowser/node_modules/webpack-chain/src/Config.js:129:40)
[1]     at Service.resolveWebpackConfig (/opt/fb_container/filebrowser/node_modules/@vue/cli-service/lib/Service.js:277:34)
[1]     at PluginAPI.resolveWebpackConfig (/opt/fb_container/filebrowser/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
[1]     at serve (/opt/fb_container/filebrowser/node_modules/@vue/cli-service/lib/commands/serve.js:79:31)
[1]     at Service.run (/opt/fb_container/filebrowser/node_modules/@vue/cli-service/lib/Service.js:262:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] vue-cli-service serve exited with code 1`
#######
Is there any outdated dependency?

**Comment by andrewscaya** [comment]
Hi @JPKairos,

For development purposes, we recommend that you use Docker with Linux for Composer to set things up, because the dependencies will be totally satisfied by this environment.

You can check out the included configuration, in order to determine how to reproduce this environment using other Docker/Linux environments, if this is what you prefer:

https://github.com/linuxforphp/filebrowser/blob/master/linuxforcomposer.json

Many thanks for your interest in the File Browser project!

Best regards,

Andrew

**Comment by andrewscaya** [comment]
Ref.: https://filebrowser.readthedocs.io/en/latest/development.html#project-setup-for-development-linux
